sudo: required
services:
  - docker

before_install:
  - docker build -t dkon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dkon/react-test npm test -- --coverage

after_success:
  - docker build -t dkon/multi-client ./client
  - docker build -t dkon/multi-nginx ./nginx
  - docker build -t dkon/multi-server ./server
  - docker build -t dkon/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dkon/multi-client
  - docker push dkon/multi-nginx
  - docker push dkon/multi-server
  - docker push dkon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-371319666489
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY